### ISSUE TITLE
When displaying XML examples, don't rewrite the root element to `<hash>`

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#1301]
## Description

In my OpenAPI spec example, I have a response with an example that looks like this:

```
      responses:
        '200':
          description: The current balance of your account
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/accountBalance'
              example: >-
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <accountBalance>
                  <value>10.17127500</value>
                  <autoReload>false</autoReload>
                </accountBalance>
```
## What did you expect to happen?

The example to be displayed in the docs

## What actually happened?

The `<accountbalance>` tag has become a `<hash>` tag!

![screenshot from 2018-12-13 18-32-37](https://user-images.githubusercontent.com/172607/49959459-8240bc00-ff05-11e8-8446-dbb4597e45a1.png)

## Steps to reproduce:

Add an XML response to your API spec document and see how it looks on NDP.

**Comment by mheap** [comment]
This turns out to be a docs issue. To specify the root node name you in an OAS document you provide the following at the schema level (https://swagger.io/specification/#xmlObject):

```
xml:
  name: accountBalance
```

See https://github.com/Nexmo/api-specification/commit/ecd74ebc7c3b6949f12418bf8393e534153cfed7 for an example that makes it render `accountBalance` rather than `hash`.
