### ISSUE TITLE
PHP code highlighting not working in Application API Reference Page

### ISSUE THREAD

**Issue by o-rod-1** [Nexmo/nexmo-developer#181]
## Description

PHP Code highlighting is working for the following PHP code snippet section
https://developer.nexmo.com/api/application#create-an-application

But is not working for the other PHP sections on that page. As an example, take a look here
https://developer.nexmo.com/api/application#retrieve-your-applications

I also noticed that the ones that are not highlighted are missing the opening PHP tag
<?php

**Comment by o-rod-1** [comment]
![2017-07-07 15_51_09-nexmo developer _ application _ api reference](https://user-images.githubusercontent.com/10967425/27979692-bbf171ea-632c-11e7-83eb-b6285268bbe9.png)
![Uploading 2017-07-07 15_50_38-Nexmo Developer _ Application _ API Reference.png…]()

**Comment by adambutler** [comment]
Thanks for reporting this issue @o-rod-1.

The behaviour is working as expected. The opening `<?php` tags are required but were missing in some examples.

This has been fixed by https://github.com/Nexmo/nexmo-developer/pull/182 which is now in production.

I'll do a full review tomorrow to ensure we've not got any other missing opening tags on other pages.
