### ISSUE TITLE
404 Error when calling send_speech() or requests.put()

### ISSUE THREAD

**Issue by andrewjylee** [Nexmo/nexmo-developer#193]
## Description

I'm trying to make my webserver respond to its callers using voice. I've tried both
https://github.com/Nexmo/nexmo-developer/blob/master/_examples/api/voice/calls/talk/update/Python and
https://github.com/Nexmo/nexmo-python/blob/master/nexmo/__init__.py#L228
but whenever I put in a put request, I get a 404 error. Perhaps I'm using it wrong - I'm not entirely sure what to put in for `uuid` nor where to get a `uuid` from.

## What did you expect to happen?

I expect to hear synthasized voice audio from the phone when that line of code is hit

## What actually happened?

a 404 error when either `client.send_speech()` or `reqeusts.put()` is hit

**Comment by tommorris** [comment]
Hi @andrewjylee,

When you send in `client.send_speech()`, you need to have an ongoing call in progress. When you start a call, Nexmo's API will send you the UUID. If you don't have an ongoing call, you don't need to use the update method on it. The point of that example code is to show how one would update an existing call - for instance, you might have a call ongoing where two users are chatting, then you wish to "break in" to that call by reading out a report to all those on the call - that's when you'd want to use the update functionality. A 404 would occur because there's no call for you to update.

If you simply wish to provide a text-to-speech response to an incoming call, you don't need to use the update call method. Instead, you should set up an HTTP endpoint that respond to an incoming webhook with the appropriate NCCO for a text-to-speech call. I've posted an example of this [up on Gist here](https://gist.github.com/tommorris/067b562db0323c78bf1d73a3147abb41). I'll update the [relevant page of the documentation](https://developer.nexmo.com/voice/building-blocks/receive-a-phone-call) with more examples of this in other languages shortly. (Our documentation on this isn't great right now. Sorry about that.)

**Comment by sammachin** [comment]
related to https://github.com/Nexmo/nexmo-python/issues/45

**Comment by tommorris** [comment]
I'm going to close this in favour of the discussion happening in one place: Nexmo/nexmo-python#45.
