### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by adambutler** [Nexmo/nexmo-developer#198]
## Description

Jack mentioned it would be good to bring the nexmo.com footer into Nexmo Developer. I think it's a little too loaded for a documentation site & goes against one of the values of being Developer centric and putting simplicity first.

I do however agree that the current footer has not had much thought put into it and think there are elements of the nexmo.com footer that we could incorporate such as:

- API Status
- The get to know us section
- Links to support
- LinkedIn Link (currently missing)

Possibly even:

- Contact details
- Traditional footer Link Terms, Privacy Policy etc.
- Products (if done in a way that wasn't confusing, I'd suggest having a generic link back to nexmo.com would be more appropriate)

**Comment by leggetter** [comment]
Link to the Slack community invite page?

**Comment by sammachin** [comment]
The idea of status being on nexmostatus.com is that it isn't tied to any of the nexmo infrastucture even the DNS for nexmo.com (it used to be status.nexmo.com) so if we have an outage of DNS (like we did last oct) its still accessable, we should be encouraging users to visit and bookmark nexmostatus.com rather than importing the status feed into developer.nexmo.com

**Comment by adambutler** [comment]
![image](https://user-images.githubusercontent.com/1238468/30320182-cdbcb9fa-97a9-11e7-8e67-40071a9a1415.png)

☝️ Proposed design, feedback welcome.

**Comment by BennyZ28** [comment]
Looks awesome!

**Comment by adambutler** [comment]
Fixed by #343
