### ISSUE TITLE
Internal_ERR while using Nexmo APi.

### ISSUE THREAD

**Issue by sheikhrashid** [Nexmo/nexmo-developer#548]
I have seen in the documentation:

**Internal Error** = An error occurred processing this request in the Cloud Communications Platform.

I am facing this error while development in Android. What does it mean? Why it is happening?

**Comment by adambutler** [comment]
Hi @sheikhrashid, sorry you are experiencing issues. To help us find the root cause of these errors it would be helpful if you could provide the following:

1. The URL in which the error occurs.
2. Your browser user agent, you can find this by going to http://whatsmyuseragent.org/

In the meantime, I'll take a look at our logs to see if anything obvious stands out there.
