### ISSUE TITLE
Cannot link to Stitch documentation with a language/platform pre-selected

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-developer#636]
## Description

How can I provide a link to https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation with iOS preselected?

## What did you expect to happen?

I'd expect the following URLs to be valid:

https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/javascript
https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/android
https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation/ios

**Comment by adambutler** [comment]
This has already been fixed by #629 

The current implementation in production was a little hacked together due to time constraints and requires using a URL parameter (i.e. `platform=ios`).

Here is a working URL: https://developer.nexmo.com/stitch/in-app-messaging/guides/1-simple-conversation?platform=ios

The implementation in #629 cleans up the live implementation as well as improves the handling of languages and platforms and is currently being reviewed by @tbedford.

**Comment by adambutler** [comment]
PR #629 has been merged resolving this issue.
