### ISSUE TITLE
Building Blocks: language tabs not highlighted

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#975]
## Description

E.g. https://nexmo-developer-staging-pr-825.herokuapp.com/voice/voice-api/building-blocks/earmuff-a-call the tabbed language choice needs to be much stronger and particularly the highlighted option. Compare with our current setup: https://developer.nexmo.com/voice/voice-api/building-blocks/earmuff-a-call

**Comment by mheap** [comment]
I gathered feedback from @marklewin who's new to the team (2 weeks) and hasn't really interacted with the existing site yet.

From Mark:

1. I don’t think the tabs are clear enough. The mouseover effect is nice to look at, but it’s not sufficiently different in colour from the selected tab to be obvious. And does it really add anything?
Also, I note that the tab doesn’t actually become selected until after you have moved the mouse cursor away from it. (Try it: click a tab, keep the mouse cursor where you clicked and then move away.)
2. I prefer our current setup because it is much clearer.
3. I do like the animated dropdowns for “Initialize Dependencies” and the other sections, but I wonder if they would become annoying if the text in one of those sections was especially long? Also, when I visit another page and come back to it, they stop working for me.

I strongly agree with item 1 - the tabs aren't clear enough for me and there's a bug with active/hover state

**Comment by BennyZ28** [comment]
You're right there's a bug with active/hover, I'll fix that on Volta. There
shouldn't be a hover state on active tabs.

I honestly don't know how to make them clearer though, that's their design.
What is it that you don't find clear? The active tabs, I already made it
coloured when normally it isn't and it matches the colour of the box
underneath which gives it a visual shape that's easy to recognise as 'tab'.
Is it that it's hard to understand you can click on the others?

I'm hoping that the fix of the bug will make them clear for everyone.

(don't think I follow point 3?)

**Comment by mheap** [comment]
I think it's both - the active state isn't bold enough and it's not clear that you can click the other languages.

This is a terrible mockup using chrome dev tools, but using a design similar to the old site but with new colours is more obvious to me (`curl` is hover, `java` is active)

![screen shot 2018-09-25 at 17 38 08](https://user-images.githubusercontent.com/59130/46028922-ca5ff780-c0e9-11e8-8d38-0d3b366e9ac3.png)

**Comment by mheap** [comment]
User feedback sounds good to me. @marklewin is the only new-to-Nexmo person that we tested with and his feedback is above.

The current suggestion of tab is a new type of tab for Volta, introduced for NDP I believe (the previous one was a blue underline). This leads me to believe that for the right use case we could have a tabbed interface that is slightly difference.

**Comment by BennyZ28** [comment]
Yes this new tab was introduced for NDP and for the Volta documentation
itself which in the near future will have language options. So, yes we can
tweak it a bit, but it does still have to be in line with the general Volta
style, hence why it has to pass through Ken.

It was a good shout to show everything to someone new but if it's still
about making a comparison between the old and the new it'd defeat the
purpose, we'd have to get someone new that goes on the page and is able or
unable to tell that those are tabs and which one is selected.

**Comment by BennyZ28** [comment]
I gave another go at the tabs, adding separators between the inactive ones to make them look more clickable and increasing the shadow around the active one. And fixed the bug. I do hope this is enough otherwise we'll have to find users to test with :)

**Comment by mheap** [comment]
The shadow and separators really help 🙌 

It looks as though the top border for the code block only goes as far as the last language e.g. Ruby on https://nexmo-developer-staging-pr-825.herokuapp.com/voice/voice-api/building-blocks/earmuff-a-call

**Comment by BennyZ28** [comment]
Yeah I forgot to fix that before deploying so it’ll go up next time. Phew
for the rest!
