### ISSUE TITLE
Developer Preview menu label layout

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-developer#982]
## Description

The "developer preview" labels (look in the Voice API docs for an example: Lex Connector https://nexmo-developer-staging-pr-825.herokuapp.com/voice/voice-api) is sort of floating equally between two menu items. It actually applies to the item above it in the menu, this could be clearer.

**Comment by mheap** [comment]
I'm not keen on shortening it as it has a very specific meaning.

Here's how it currently looks:

![screen shot 2018-09-25 at 16 50 15](https://user-images.githubusercontent.com/59130/46026421-35f29680-c0e3-11e8-92b0-2a87a2baa94b.png)

I don't think it's great on the existing site either

Could we have it multi-line like it is in Volta now, but saying `Developer Preview` rather than `DP`?

![screen shot 2018-09-25 at 16 52 03](https://user-images.githubusercontent.com/59130/46026482-591d4600-c0e3-11e8-9ceb-215da020d3d2.png)

**Comment by BennyZ28** [comment]
So, yes we can, BUT:
- If we have it the way we normally deal with badges on volta, it will stay
glued to the right-hand side, and a large label means a lot of wrapping of
the menu item label.
- If we have it the way it was before, I have to manually add margin to the
bottom so that it won't wrap...

Hence why I was suggesting a shorter label, whichever way we do it it's
gonna not look great :(

**Comment by mheap** [comment]
Could we try it another way, where `Beta` and `Developer Preview` become icons with tooltips? Less space taken up, but the information is still available. I'm not too sure how accessible tooltips are though

**Comment by BennyZ28** [comment]
Sure we can try, altho have a look at the solution I pushed yesterday, I
put back "developer preview" with a different padding

**Comment by mheap** [comment]
This puts it back to how it was, which I think is good enough to let us go forwards. Longer term I'd like to revisit how we label things in general

**Comment by BennyZ28** [comment]
Yes, I was just able to fix the spacing issue. Long term plan sounds good.

**Comment by lornajane** [comment]
Going to close this one as I think what we have is good for now. Thanks @BennyZ28 !
